name: Commitizen Bump Manager

on:
  push:
    branches: [ "master" ]

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: commitizen-tools/setup-cz@main
        with:
          python-version: "3.x"
      - run: |
          cz version -p
          cz bump --yes --annotated-tag
          cz changelog
          git add CHANGELOG.md
          git commit -m "feature(changelog): updated for version $(cz version -p)"
          git push --follow-tags
          git push origin master
