name: Workflow security audit
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

permissions: {}

jobs:
  zizmor:
    name: Scan zizmor
    runs-on: ubuntu-latest
    permissions:
      # Upload SARIF
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Installzizmor
        run: pipx install zizmor

      - name: Scan workflows
        run: zizmor --format=sarif --offline .github/workflows/ > results.sarif
        continue-on-error: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@ea9e4e37992a54ee68a9571ad585dd722115571f # v3.28.14
        with:
          sarif_file: results.sarif
          category: zizmor
